version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/shopface-refactor/
    overwriter: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: execute-deploy.sh
      timeout: 100
      runas: ec2-user