spring:
  profiles:
    include: aws, db, mail
  mvc:
    log-request-details: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  error:
    include-stacktrace: never

