spring:
  profiles:
    include: aws, db, mail
  mvc:
    log-request-details: true

logging:
  level:
    org.springframework.web: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE


server:
  error:
    include-stacktrace: never