spring:
  profiles:
    active: local
---
spring:
  profiles:
    include: aws, db
  mvc:
    log-request-details: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  error:
    include-stacktrace: never

---
spring:
  profiles: prod

spring:
  profiles:
    include: aws, db
  mvc:
    log-request-details: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

server:
  error:
    include-stacktrace: never
